@host = http://localhost:9191
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMWMyMDQ4NjYtYTRkZS00ZmVkLWI0OWMtMTg1NzgwMTRmOTllIiwiaWF0IjoxNzE5Mjc5MjUwLCJleHAiOjE3MTkzMDA4NTAsImp0aSI6IjVmN2M4MzY5LWE2ZWEtNDY2Mi04MzM2LTg0YjFlZjI0YTJhNCJ9.Ng_cd8_sCmXgLrDWx-N06-grekdcXeYX6m_h-iiuPOA

###
POST {{host}}/authentication/login
Content-Type: application/json

{
    "username":"19931120211014",
    "password":"bismillah212",
    "system":"apakah"
}

###
GET {{host}}/ptk

###
GET {{host}}/account/page?page=1&size=1
Authorization: Bearer {{token}}

###
GET {{host}}/account/group_account/1
Authorization: Bearer {{token}}
###
GET {{host}}/account


###
GET {{host}}/detail-of-activity/institution

###
GET {{host}}/disbursement-of-fund/status/1?page=1&size=5

###
GET {{host}}/disbursementOfFund/activity/a4d57988-11dd-4859-b973-88d207444908

###
PUT {{host}}/disbursementOfFund/status/4e9abebd-4d22-4878-aa4b-eb7337c37bae

###
PUT {{host}}/disbursementOfFund/withdraw/9ce78171-065a-4674-8ae0-49cdfb6f68b9

###
GET {{host}}/institution

###
POST {{host}}/detail-of-activity/institution
Content-Type: application/json

{
    "institutionId":1
}

###
GET {{host}}/journal?page=1&size=5&`from_date=2024-04-01&to_date=2024-04-30
Authorization: Bearer {{token}}
###
GET {{host}}/journal/account/account-begining-balance
###
POST {{host}}/journal/account/account-begining-balance
Content-Type: application/json

{
    "harta":[
        {
            "value":10000,
            "id":"ff87dec6-754a-483f-bf87-3417687cfb1e"
        },
        {
            "value":20000,
            "id":"b95613de-ef94-4c5a-89c4-2e5bcdb7ef4e"
        }
    ]
}

###
POST  {{host}}/journal/monthly-account/close-book/?month_index=3

###
GET {{host}}/report/balance-statement?month_index=4
###
GET {{host}}/report/cash-flow-statement?month=5
###
GET {{host}}/ledger
###
GET {{host}}/ledger/detail?id=78f4ed6f-8e62-4e84-a80e-a209db1fecb4&month=6
###
GET {{host}}/apakah/list-lembaga-apakah
###
POST {{host}}/apakah/list-lembaga-apakah
Content-Type: application/json

{
    "nama":"testing"
}
###
POST {{host}}/apakah/program
Content-Type: application/json

{
   "institution_id":"1",
   "item":"Beli PS5"
}
###
POST  {{host}}/apakah/institution-income
Content-Type: application/json

{
    "institution_id":2,
    "academic_year":"2024/2025",
    "total":3000000,
    "approved_total":0
}
###
GET {{host}}/apakah/institution-income/2?status_incomes=0
###
PUT {{host}}/apakah/institution-income/approval/
###
PUT {{host}}/apakah/institution-income/approval/9e3b9c9a-e4ac-4171-8b50-891510ae1387
Content-Type: application/json

{
    "approved_total":150000
}
###
PUT {{host}}/apakah/institution-income/9b1ffb78-01e7-449f-b935-b6eff3a11693
Content-Type: application/json

{
    "total":150000,
    "academic_year":"2023/2024"
}
###
POST {{host}}/institution
Content-Type: application/json

{
    "name":"SD IT PUTRI",
    "academic_year":"2024/2025"
}

###
GET {{host}}/institution
###
GET {{host}}/apakah/unit
###
POST {{host}}/apakah/component
Content-Type: application/json

{
    "item":"Sarana Games dan Refreshing",
    "program_id":"20599dd5-9fec-43fc-b833-606091116697"
}
###
POST  {{host}}/apakah/activity
Content-Type: application/json

{
    "component_id":"120139ab-fdfd-4956-9dbe-0916699a5d13",
    "name":"Mak Cong",
    "continue_activity":true
}
###
POST {{host}}/apakah/sub-activity
Content-Type: application/json

{
    "activity_id":"6118ceaf-1f2c-4570-9921-66df7bbefea4",
    "name":"GTR"
}
###
POST {{host}}/apakah/detail-of-activity
Content-Type: application/json

{
    "activity_id":"110e2471-e893-4098-86b1-5f6aa0a93a29",
    "sub_activity_id":null,
    "detail_of_activity_list":[
        {
            "description":"blablabla",
            "unit_id":"2", 
            "vol":2,
            "unit_price":1,
            "thawing_method":"semester",
            "from":1,
            "until":12,
            "total":9000000000000000000000000,
            "academic_year":"2024/2025",
            "sharing_program":true,
            "post":1,
            "institution_income_id": "3e97c4fa-e101-4c5f-bf16-a0ad7e17f420"
        }
    ]
}
###
GET  {{host}}/apakah/program/24?academic_year=2024-2025
Authorization: Bearer {{token}}
###
GET {{host}}/apakah/component/f852d701-7dde-4cae-91cc-25cc389c858b
###
GET {{host}}/apakah/activity/f852d701-7dde-4cae-91cc-25cc389c858b
###
GET {{host}}/apakah/detail-of-activity/6118ceaf-1f2c-4570-9921-66df7bbefea4
###
GET {{host}}/apakah/detail-of-activity/sub/438abe0f-dab4-4e37-9d32-2044e46d1465
###
POST {{host}}/apakah/income-group
Content-Type: application/json

{
    "name":"test",
    "parent_id":20222
}

###
GET {{host}}/year-active-system?system=kuc
###
GET {{host}}/apakah/institution-income/1?academic_year=2024-2025
###
DELETE {{host}}/apakah/detail-of-activity/
###
DELETE {{host}}/apakah/sub-activity/ab5c2afb-6a59-4974-a37e-3bfa432d9509
###
DELETE {{host}}/apakah/detail-of-activity/71612035-0e41-47b5-b01a-94cdbfe73a7b
###
GET {{host}}/apakah/dashboard
###
GET {{host}}/apakah/dashboard/24
Authorization: Bearer {{token}}
###
GET {{host}}/apakah/weight-activity
###
GET {{host}}/apakah/weight-activity/question
###
POST  {{host}}/apakah/weight-activity/answer
Content-Type: application/json

{
    "activity_id":"e8a8db4e-26b7-4e25-9e08-f44eeb015063",
    "answer":[
        {
            "question_id":1,
            "answer_id":1,
            "weight":1
        }
    ]
}


